CREATE DATABASE PBL;

CREATE TABLE JOB_POSTING(POSTID INT IDENTITY(1,1) PRIMARY KEY, COMPANYNAME VARCHAR(150), JOBFIELD VARCHAR(100), CITY VARCHAR(150),COUNTRY VARCHAR(60), SALARY INT, DESCIPT VARCHAR(1000),QUALI VARCHAR(1000),DETAILS VARCHAR(1000));

CREATE TABLE USER_ACCOUNTS(FIRST_NAME VARCHAR(150), LAST_NAME VARCHAR(150), EMAIL VARCHAR(150) PRIMARY KEY, GENDER VARCHAR(150), CITY VARCHAR(150), COUNTRY VARCHAR(150), PASSWARD VARCHAR(150), CONFIRMED_PASSWARD VARCHAR(150), AGE INT );

ALTER TABLE JOB_POSTING ADD POSTDATE DATETIME;

SELECT * FROM JOB_POSTING;
SELECT * FROM USER_ACCOUNTS;

CREATE TABLE dbo.UserData(EMAIL varchar(150), ABOUT_ME text, EDUCATION text, WORK text, SKILLS text, JOB varchar(50));
SELECT * FROM dbo.UserData;
SELECT * FROM dbo.USER_ACCOUNTS;
INSERT INTO dbo.UserData(EMAIL) VALUES('test');
DELETE FROM dbo.USER_ACCOUNTS;
DELETE FROM dbo.UserData;