//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_POSTING
    {
        public int POSTID { get; set; }
        public string COMPANYNAME { get; set; }
        public string JOBFIELD { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<int> SALARY { get; set; }
        public string DESCIPT { get; set; }
        public string QUALI { get; set; }
        public string DETAILS { get; set; }
        public Nullable<System.DateTime> POSTDATE { get; set; }
    }
}
