//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ACCOUNTS
    {
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string EMAIL { get; set; }
        public string GENDER { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
        public string PASSWARD { get; set; }
        public string CONFIRMED_PASSWARD { get; set; }
        public Nullable<int> AGE { get; set; }
    }
}
